// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR599m9RWeT7s33izl6syDajbRBgQPkos',
    appId: '1:766720889151:web:4c871e6e18e0a6bfb0038a',
    messagingSenderId: '766720889151',
    projectId: 'insta-demo-237ef',
    authDomain: 'insta-demo-237ef.firebaseapp.com',
    storageBucket: 'insta-demo-237ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxhyYUTPUPeuWj9yaz99E0eonsCxbEo4',
    appId: '1:766720889151:android:4a8bb4fa0b4d1028b0038a',
    messagingSenderId: '766720889151',
    projectId: 'insta-demo-237ef',
    storageBucket: 'insta-demo-237ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIjGfwVR4ikVrAdLDCLOgNjW_VhNJ_QM',
    appId: '1:766720889151:ios:9f7e3346fab3e7ccb0038a',
    messagingSenderId: '766720889151',
    projectId: 'insta-demo-237ef',
    storageBucket: 'insta-demo-237ef.firebasestorage.app',
    iosBundleId: 'com.example.instaDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXIjGfwVR4ikVrAdLDCLOgNjW_VhNJ_QM',
    appId: '1:766720889151:ios:9f7e3346fab3e7ccb0038a',
    messagingSenderId: '766720889151',
    projectId: 'insta-demo-237ef',
    storageBucket: 'insta-demo-237ef.firebasestorage.app',
    iosBundleId: 'com.example.instaDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR599m9RWeT7s33izl6syDajbRBgQPkos',
    appId: '1:766720889151:web:1676b48d498334c4b0038a',
    messagingSenderId: '766720889151',
    projectId: 'insta-demo-237ef',
    authDomain: 'insta-demo-237ef.firebaseapp.com',
    storageBucket: 'insta-demo-237ef.firebasestorage.app',
  );
}
